### ISSUE TITLE
Please tell me how combo-select can support onchange event? thanks

### ISSUE THREAD

**Issue by Tangoy** [PebbleRoad/combo-select#11]

**Comment by rmdort** [comment]
Just bind to change event on the select element

https://github.com/PebbleRoad/combo-select/blob/master/index.html#L175

**Comment by Tangoy** [comment]
I write the select element in a form, and bind to change event on the select element,but it doesn't work.thanks

**Comment by rmdort** [comment]
Pls share your code on jsbin or jsfiddle
