### ISSUE TITLE
Adding items to dropdown, calling function to update the virtual (ul, li) dropdown

### ISSUE THREAD

**Issue by abhishek238** [PebbleRoad/combo-select#2]
I was just adding some options to the native dropdown and called the plugin, i am getting black screen, so can not a call the plugin multiple times after page load, i just set a "setInterval" to initialize the function again and again, and after a few times it sucks!

**Comment by rmdort** [comment]
Fixed. Added a new `comboselect:update` event to trigger updates.

**Comment by abhishek238** [comment]
can you please show me an example for update the combo box, i didnt got it :(

**Comment by rmdort** [comment]
Here: http://pebbleroad.github.io/combo-select/
