### ISSUE TITLE
Input box get cleared some time when the user tab out.

### ISSUE THREAD

**Issue by hiranpodi** [PebbleRoad/combo-select#3]
Instead of picking something from the list if you type new text in the iput box and tab bout some times it get cleared.

**Comment by rmdort** [comment]
Can you create a jsfiddle.

**Comment by hiranpodi** [comment]
Hi, You can use your own demo. 

Select "03" form the "Select Day" combo. Then Change it to 40 and tab out.

BTW what is the licencing model for this if I want to use this in a commercial app. Thx

**Comment by rmdort** [comment]
This is the expected behavior.You are entering an invalid value.

You can use it anyway you want. Its MIT licensed.
