### ISSUE TITLE
Firefox Bug - Selection goes to default value after clicking anywhere on the screen.

### ISSUE THREAD

**Issue by hristokkanchev** [PebbleRoad/combo-select#5]
Info:
Firefox version - 45.0.1
OS - Windows 10

Link:
http://codepen.io/hristokkanchev/pen/mPZGyN

Steps to reproduce:
1. Select 1 or 2 from the combo-select dropdown.
2. Click anywhere (the select arrow or anywhere else except the input).
3. Selection goes back to Select value and doesn't retain it's selected value.

All of the code used in the pen is from the example.

Please address this issue as soon as possible since I am trying to use this library in a production based environment.

**Comment by hristokkanchev** [comment]
@rmdort Any ideas?

**Comment by rmdort** [comment]
Pushed a fix for this. Hope that fixes the firefox issue.

**Comment by hristokkanchev** [comment]
Awesome! Thank you so much!
