### ISSUE TITLE
How to add a custom style for data- or html tag

### ISSUE THREAD

**Issue by lowpez** [PebbleRoad/combo-select#7]
Hi there PebbleRoad Team,
What im trying to acomplish is append some extra data to my optionbox.
This data should be presented with a different font-size and color for  a better visual experience.
Could you tell me if this feature is already implemented or how to make it possible?.

```
<select>
<option>Vitto Bratta <small>23 Street NY</small></option>
<option data-st="23 Street NJ">Jimmmy Page</small></option>
</select>
```

Thanks a Lot!

**Comment by rmdort** [comment]
Currently no. But you could send me a pull request to customize display template
