### ISSUE TITLE
ADA Compliance Issue - form control missing label when appending input to the DOM

### ISSUE THREAD

**Issue by malcolmbyrd** [PebbleRoad/combo-select#9]
Hi,

This issue is minor, but important.  My company's client, NYC Department of Finance, got an ADA Compliance warning for a missing label on a form control. It was easy to track down, but I noticed it was code from a github repo, so here I am:

In jquery.combo.select.js , the following input should have a label attribute:
**line 173**: this.$input = $('<input **_label="dropdown-input"_** type="text"' + (isMobile? 'tabindex="-1"': '').....

**Comment by rmdort** [comment]
Can u send me a pull request to fix this

**Comment by maish** [comment]
how to do this? you have all the passwords.

**Comment by malcolmbyrd** [comment]
I created the pull request this morning.
